**One Hot Encoding or Nominal Encoding**

In [19]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [4]:
df = pd.DataFrame({'color':['red','blue','green','green','red','blue']})

In [37]:
# df

In [7]:
 # create an instance of OneHotEncoder
ohe = OneHotEncoder()

In [25]:
# perform fit and transform
sparse_matrix = ohe.fit_transform(df[['color']])

In [26]:
sparse_matrix

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [33]:
sparse_matrix=sparse_matrix.toarray()

In [34]:
# from OneHotEncoder instance we can see the new features created
ohe.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [35]:
# Create the dataframe
ohe_df = pd.DataFrame(sparse_matrix,columns=ohe.get_feature_names_out())

In [36]:
ohe_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [38]:
# How to deal with new data
ohe.transform([['blue']]).toarray()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [39]:
new_df = pd.concat([df,ohe_df],axis=1)
new_df.head()

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0

**Label Encoding**

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
df

color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [42]:
#Create instance
label_enc = LabelEncoder()

In [43]:
label_enc.fit_transform(df[['color']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [44]:
# new value encoding
label_enc.transform([['blue']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

**Ordinal Encoding**

In [47]:
from sklearn.preprocessing import OrdinalEncoder

In [49]:
# Create an instance of Ordinal Encoder
oe = OrdinalEncoder()

In [50]:
df_ordinal = pd.DataFrame({'size':['small','medium','large','medium','small','large']})

In [53]:
# df_ordinal

In [56]:
# Let's assing ranking or order
ranks = [['small','medium','large']]

In [60]:
oe=OrdinalEncoder(categories=ranks)

In [61]:
oe.fit_transform(df_ordinal[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [62]:
# New data
oe.transform([['medium']])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1.]])

**Target Guided Ordinal Encoding**

In [63]:
df = pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [66]:
mean_values = df.groupby('city')['price'].mean().to_dict()
mean_values

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [67]:
df['city_encoded'] = df['city'].map(mean_values)

In [69]:
df

city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0