In [5]:
from sklearn.datasets import load_iris
import pandas as pd

In [3]:
X,y = load_iris(return_X_y=True)
# it will return numpy array

In [10]:
df = pd.DataFrame(X)

In [11]:
df.head(1)

0    1    2    3
0  5.1  3.5  1.4  0.2

data is continuous so we can use Gaussian Naive Bayes

In [12]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(df,y,test_size=0.3)

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
gnb = GaussianNB()

In [19]:
gnb.fit(X_train,y_train)

GaussianNB()

In [20]:
y_pred = gnb.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 16  1]
 [ 0  1 13]]


In [24]:
print(accuracy_score(y_test,y_pred))

0.9555555555555556


In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        17
           2       0.93      0.93      0.93        14

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

